/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package evgn.dev.messaging.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DialogMessage service. Represents a row in the &quot;dmsg_DialogMessage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link evgn.dev.messaging.model.impl.DialogMessageModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link evgn.dev.messaging.model.impl.DialogMessageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DialogMessage
 * @see evgn.dev.messaging.model.impl.DialogMessageImpl
 * @see evgn.dev.messaging.model.impl.DialogMessageModelImpl
 * @generated
 */
@ProviderType
public interface DialogMessageModel extends BaseModel<DialogMessage> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dialog message model instance should use the {@link DialogMessage} interface instead.
	 */

	/**
	 * Returns the primary key of this dialog message.
	 *
	 * @return the primary key of this dialog message
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dialog message.
	 *
	 * @param primaryKey the primary key of this dialog message
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the message ID of this dialog message.
	 *
	 * @return the message ID of this dialog message
	 */
	public long getMessageId();

	/**
	 * Sets the message ID of this dialog message.
	 *
	 * @param messageId the message ID of this dialog message
	 */
	public void setMessageId(long messageId);

	/**
	 * Returns the dialog ID of this dialog message.
	 *
	 * @return the dialog ID of this dialog message
	 */
	public long getDialogId();

	/**
	 * Sets the dialog ID of this dialog message.
	 *
	 * @param dialogId the dialog ID of this dialog message
	 */
	public void setDialogId(long dialogId);

	/**
	 * Returns the text of this dialog message.
	 *
	 * @return the text of this dialog message
	 */
	@AutoEscape
	public String getText();

	/**
	 * Sets the text of this dialog message.
	 *
	 * @param text the text of this dialog message
	 */
	public void setText(String text);

	/**
	 * Returns the dialog member ID of this dialog message.
	 *
	 * @return the dialog member ID of this dialog message
	 */
	public long getDialogMemberId();

	/**
	 * Sets the dialog member ID of this dialog message.
	 *
	 * @param dialogMemberId the dialog member ID of this dialog message
	 */
	public void setDialogMemberId(long dialogMemberId);

	/**
	 * Returns the user ID of this dialog message.
	 *
	 * @return the user ID of this dialog message
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this dialog message.
	 *
	 * @param userId the user ID of this dialog message
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dialog message.
	 *
	 * @return the user uuid of this dialog message
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dialog message.
	 *
	 * @param userUuid the user uuid of this dialog message
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this dialog message.
	 *
	 * @return the create date of this dialog message
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this dialog message.
	 *
	 * @param createDate the create date of this dialog message
	 */
	public void setCreateDate(Date createDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(evgn.dev.messaging.model.DialogMessage dialogMessage);

	@Override
	public int hashCode();

	@Override
	public CacheModel<evgn.dev.messaging.model.DialogMessage> toCacheModel();

	@Override
	public evgn.dev.messaging.model.DialogMessage toEscapedModel();

	@Override
	public evgn.dev.messaging.model.DialogMessage toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}