/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package evgn.dev.messaging.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the DialogMember service. Represents a row in the &quot;dmsg_DialogMember&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link evgn.dev.messaging.model.impl.DialogMemberModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link evgn.dev.messaging.model.impl.DialogMemberImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DialogMember
 * @see evgn.dev.messaging.model.impl.DialogMemberImpl
 * @see evgn.dev.messaging.model.impl.DialogMemberModelImpl
 * @generated
 */
@ProviderType
public interface DialogMemberModel extends BaseModel<DialogMember> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dialog member model instance should use the {@link DialogMember} interface instead.
	 */

	/**
	 * Returns the primary key of this dialog member.
	 *
	 * @return the primary key of this dialog member
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dialog member.
	 *
	 * @param primaryKey the primary key of this dialog member
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the dialog member ID of this dialog member.
	 *
	 * @return the dialog member ID of this dialog member
	 */
	public long getDialogMemberId();

	/**
	 * Sets the dialog member ID of this dialog member.
	 *
	 * @param dialogMemberId the dialog member ID of this dialog member
	 */
	public void setDialogMemberId(long dialogMemberId);

	/**
	 * Returns the dialog ID of this dialog member.
	 *
	 * @return the dialog ID of this dialog member
	 */
	public long getDialogId();

	/**
	 * Sets the dialog ID of this dialog member.
	 *
	 * @param dialogId the dialog ID of this dialog member
	 */
	public void setDialogId(long dialogId);

	/**
	 * Returns the member ID of this dialog member.
	 *
	 * @return the member ID of this dialog member
	 */
	public long getMemberId();

	/**
	 * Sets the member ID of this dialog member.
	 *
	 * @param memberId the member ID of this dialog member
	 */
	public void setMemberId(long memberId);

	/**
	 * Returns the member type of this dialog member.
	 *
	 * @return the member type of this dialog member
	 */
	@AutoEscape
	public String getMemberType();

	/**
	 * Sets the member type of this dialog member.
	 *
	 * @param memberType the member type of this dialog member
	 */
	public void setMemberType(String memberType);

	/**
	 * Returns the name of this dialog member.
	 *
	 * @return the name of this dialog member
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dialog member.
	 *
	 * @param name the name of this dialog member
	 */
	public void setName(String name);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(evgn.dev.messaging.model.DialogMember dialogMember);

	@Override
	public int hashCode();

	@Override
	public CacheModel<evgn.dev.messaging.model.DialogMember> toCacheModel();

	@Override
	public evgn.dev.messaging.model.DialogMember toEscapedModel();

	@Override
	public evgn.dev.messaging.model.DialogMember toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}