/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package evgn.dev.messaging.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import evgn.dev.messaging.model.Dialog;
import evgn.dev.messaging.service.DialogLocalService;
import evgn.dev.messaging.service.persistence.DialogMemberPersistence;
import evgn.dev.messaging.service.persistence.DialogMessagePersistence;
import evgn.dev.messaging.service.persistence.DialogPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the dialog local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link evgn.dev.messaging.service.impl.DialogLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see evgn.dev.messaging.service.impl.DialogLocalServiceImpl
 * @see evgn.dev.messaging.service.DialogLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class DialogLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements DialogLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link evgn.dev.messaging.service.DialogLocalServiceUtil} to access the dialog local service.
	 */

	/**
	 * Adds the dialog to the database. Also notifies the appropriate model listeners.
	 *
	 * @param dialog the dialog
	 * @return the dialog that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Dialog addDialog(Dialog dialog) {
		dialog.setNew(true);

		return dialogPersistence.update(dialog);
	}

	/**
	 * Creates a new dialog with the primary key. Does not add the dialog to the database.
	 *
	 * @param dialogId the primary key for the new dialog
	 * @return the new dialog
	 */
	@Override
	public Dialog createDialog(long dialogId) {
		return dialogPersistence.create(dialogId);
	}

	/**
	 * Deletes the dialog with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param dialogId the primary key of the dialog
	 * @return the dialog that was removed
	 * @throws PortalException if a dialog with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Dialog deleteDialog(long dialogId) throws PortalException {
		return dialogPersistence.remove(dialogId);
	}

	/**
	 * Deletes the dialog from the database. Also notifies the appropriate model listeners.
	 *
	 * @param dialog the dialog
	 * @return the dialog that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Dialog deleteDialog(Dialog dialog) {
		return dialogPersistence.remove(dialog);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Dialog.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return dialogPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link evgn.dev.messaging.model.impl.DialogModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return dialogPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link evgn.dev.messaging.model.impl.DialogModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return dialogPersistence.findWithDynamicQuery(dynamicQuery, start, end,
			orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return dialogPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return dialogPersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public Dialog fetchDialog(long dialogId) {
		return dialogPersistence.fetchByPrimaryKey(dialogId);
	}

	/**
	 * Returns the dialog with the primary key.
	 *
	 * @param dialogId the primary key of the dialog
	 * @return the dialog
	 * @throws PortalException if a dialog with the primary key could not be found
	 */
	@Override
	public Dialog getDialog(long dialogId) throws PortalException {
		return dialogPersistence.findByPrimaryKey(dialogId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(dialogLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Dialog.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dialogId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(dialogLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Dialog.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("dialogId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(dialogLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Dialog.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("dialogId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return dialogLocalService.deleteDialog((Dialog)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return dialogPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the dialogs.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link evgn.dev.messaging.model.impl.DialogModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of dialogs
	 * @param end the upper bound of the range of dialogs (not inclusive)
	 * @return the range of dialogs
	 */
	@Override
	public List<Dialog> getDialogs(int start, int end) {
		return dialogPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of dialogs.
	 *
	 * @return the number of dialogs
	 */
	@Override
	public int getDialogsCount() {
		return dialogPersistence.countAll();
	}

	/**
	 * Updates the dialog in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param dialog the dialog
	 * @return the dialog that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Dialog updateDialog(Dialog dialog) {
		return dialogPersistence.update(dialog);
	}

	/**
	 * Returns the dialog local service.
	 *
	 * @return the dialog local service
	 */
	public DialogLocalService getDialogLocalService() {
		return dialogLocalService;
	}

	/**
	 * Sets the dialog local service.
	 *
	 * @param dialogLocalService the dialog local service
	 */
	public void setDialogLocalService(DialogLocalService dialogLocalService) {
		this.dialogLocalService = dialogLocalService;
	}

	/**
	 * Returns the dialog persistence.
	 *
	 * @return the dialog persistence
	 */
	public DialogPersistence getDialogPersistence() {
		return dialogPersistence;
	}

	/**
	 * Sets the dialog persistence.
	 *
	 * @param dialogPersistence the dialog persistence
	 */
	public void setDialogPersistence(DialogPersistence dialogPersistence) {
		this.dialogPersistence = dialogPersistence;
	}

	/**
	 * Returns the dialog member local service.
	 *
	 * @return the dialog member local service
	 */
	public evgn.dev.messaging.service.DialogMemberLocalService getDialogMemberLocalService() {
		return dialogMemberLocalService;
	}

	/**
	 * Sets the dialog member local service.
	 *
	 * @param dialogMemberLocalService the dialog member local service
	 */
	public void setDialogMemberLocalService(
		evgn.dev.messaging.service.DialogMemberLocalService dialogMemberLocalService) {
		this.dialogMemberLocalService = dialogMemberLocalService;
	}

	/**
	 * Returns the dialog member persistence.
	 *
	 * @return the dialog member persistence
	 */
	public DialogMemberPersistence getDialogMemberPersistence() {
		return dialogMemberPersistence;
	}

	/**
	 * Sets the dialog member persistence.
	 *
	 * @param dialogMemberPersistence the dialog member persistence
	 */
	public void setDialogMemberPersistence(
		DialogMemberPersistence dialogMemberPersistence) {
		this.dialogMemberPersistence = dialogMemberPersistence;
	}

	/**
	 * Returns the dialog message local service.
	 *
	 * @return the dialog message local service
	 */
	public evgn.dev.messaging.service.DialogMessageLocalService getDialogMessageLocalService() {
		return dialogMessageLocalService;
	}

	/**
	 * Sets the dialog message local service.
	 *
	 * @param dialogMessageLocalService the dialog message local service
	 */
	public void setDialogMessageLocalService(
		evgn.dev.messaging.service.DialogMessageLocalService dialogMessageLocalService) {
		this.dialogMessageLocalService = dialogMessageLocalService;
	}

	/**
	 * Returns the dialog message persistence.
	 *
	 * @return the dialog message persistence
	 */
	public DialogMessagePersistence getDialogMessagePersistence() {
		return dialogMessagePersistence;
	}

	/**
	 * Sets the dialog message persistence.
	 *
	 * @param dialogMessagePersistence the dialog message persistence
	 */
	public void setDialogMessagePersistence(
		DialogMessagePersistence dialogMessagePersistence) {
		this.dialogMessagePersistence = dialogMessagePersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("evgn.dev.messaging.model.Dialog",
			dialogLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"evgn.dev.messaging.model.Dialog");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return DialogLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Dialog.class;
	}

	protected String getModelClassName() {
		return Dialog.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = dialogPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = DialogLocalService.class)
	protected DialogLocalService dialogLocalService;
	@BeanReference(type = DialogPersistence.class)
	protected DialogPersistence dialogPersistence;
	@BeanReference(type = evgn.dev.messaging.service.DialogMemberLocalService.class)
	protected evgn.dev.messaging.service.DialogMemberLocalService dialogMemberLocalService;
	@BeanReference(type = DialogMemberPersistence.class)
	protected DialogMemberPersistence dialogMemberPersistence;
	@BeanReference(type = evgn.dev.messaging.service.DialogMessageLocalService.class)
	protected evgn.dev.messaging.service.DialogMessageLocalService dialogMessageLocalService;
	@BeanReference(type = DialogMessagePersistence.class)
	protected DialogMessagePersistence dialogMessagePersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}